const stages=['AÇÃO','IDEALIZADO','ORÇADO','CONTRATADO','CONCLUÍDO','CANCELADO'];
const stageMeta={'AÇÃO':['🟡','AÇÃO'],'IDEALIZADO':['💡','IDEALIZADO'],'ORÇADO':['💰','ORÇADO'],'CONTRATADO':['📦','CONTRATADO'],'CONCLUÍDO':['✅','CONCLUÍDO'],'CANCELADO':['🚫','CANCELADO']};
const categories=[['🍽️','Comida'],['🍰','Bolo e doces'],['🥤','Bebidas'],['🎈','Decoração'],['🌸','Flores'],['🪑','Mobiliário'],['🎁','Lembrancinhas'],['📦','Embalagens'],['💌','Papelaria'],['👗','Roupa da Olga'],['👨‍👩‍👧','Convidados'],['📸','Fotografia'],['🎥','Vídeo'],['🎵','Música / DJ'],['🎤','Entretenimento'],['🏠','Local'],['🚗','Transporte'],['💄','Beleza'],['🧹','Limpeza'],['🍽️','Louças'],['🧁','Mesa de doces'],['🛍️','Compras'],['📝','Outros']];
const iconOf=c=>categories.find(x=>x[1]===c)?.[0]||'📝'; const today=new Date();
const initial=[
 {id:1,title:'Definir lista de convidados',category:'Convidados',owner:'Bruno + Mariana',stage:'AÇÃO',due:'2026-09-27',value:0,supplier:'',note:'Separar adultos e crianças'},
 {id:2,title:'Roupa da Olga',category:'Roupa da Olga',owner:'Mariana',stage:'AÇÃO',due:'2026-10-03',value:280,supplier:'Ateliê Pequena',note:'Vestido e tiara'},
 {id:3,title:'Decoração Stranger Things',category:'Decoração',owner:'Mariana',stage:'IDEALIZADO',due:'2026-09-29',value:0,supplier:'',note:'Moodboard com luzes, vermelho e azul'},
 {id:4,title:'Lembrancinhas personalizadas',category:'Lembrancinhas',owner:'Bruno',stage:'IDEALIZADO',due:'2026-10-01',value:0,supplier:'',note:'40 caixinhas de waffle'},
 {id:5,title:'Bolo da Olga',category:'Bolo e doces',owner:'Mariana',stage:'ORÇADO',due:'2026-10-05',payment:'2026-10-20',value:650,supplier:'Confeitaria Doce Dia',note:'Red velvet, 3kg'},
 {id:6,title:'Fotógrafo',category:'Fotografia',owner:'Bruno',stage:'ORÇADO',due:'2026-09-25',payment:'2026-09-25',value:1200,supplier:'Caio Luz Foto',note:'Pacote 4 horas'},
 {id:7,title:'Docinhos',category:'Bolo e doces',owner:'Mariana',stage:'CONTRATADO',due:'2026-10-24',payment:'2026-10-01',value:480,paid:240,supplier:'Delícias da Mari',note:'120 unidades, 6 sabores'},
 {id:8,title:'Bebidas',category:'Bebidas',owner:'Bruno + Mariana',stage:'CONTRATADO',due:'2026-10-23',payment:'2026-10-10',value:560,paid:0,supplier:'Adega Central',note:'Sucos, refrigerantes e água'},
 {id:9,title:'Mobiliário',category:'Mobiliário',owner:'Bruno',stage:'CONTRATADO',due:'2026-10-25',payment:'2026-09-19',value:900,paid:0,supplier:'Aluga Festa',note:'Mesas infantis e cadeiras'}
];
let items=JSON.parse(localStorage.getItem('olga-items')||'null')||initial; let selectedCategory='', editId=null;
const $=s=>document.querySelector(s); const money=n=>n?`R$ ${Number(n).toLocaleString('pt-BR',{minimumFractionDigits:0})}`:'—'; const date=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}):'—';
function save(){localStorage.setItem('olga-items',JSON.stringify(items));renderAll()}
function urgency(d){if(!d)return'';let n=Math.ceil((new Date(d+'T12:00:00')-today)/864e5);return n<0?'late':n<=3?'urgent':n<=7?'warn':''}
function ownerAvatar(o){return `<span class="mini-avatar ${o==='Mariana'?'mariana':'bruno'}">${o==='Mariana'?'M':o==='Bruno'?'B':'B+M'}</span>`}
function card(x){let u=urgency(x.due), payment=x.payment&&x.stage==='CONTRATADO'?`<div class="due ${urgency(x.payment)}">💳 Pagamento <b>${date(x.payment)}</b></div>`:'';return `<article class="card" draggable="true" data-id="${x.id}"><div class="card-title"><span>${iconOf(x.category)}</span><b>${x.title}</b></div><div class="card-cat">${x.category}</div><div class="card-person">${ownerAvatar(x.owner)} ${x.owner}</div>${x.supplier?`<div class="card-supplier">${x.supplier}</div>`:''}${x.value?`<div class="money">${money(x.value)}</div>`:''}${x.due?`<div class="due ${u}">📅 ${x.stage==='CONTRATADO'?'Entrega':'Próximo prazo'} <b>${date(x.due)}</b></div>`:''}${payment}${x.stage==='CONTRATADO'?`<div class="progress"><span style="width:${x.value?Math.round((x.paid||0)/x.value*100):0}%"></span></div>`:''}</article>`}
function renderBoard(){let term=$('#search').value.toLowerCase(),owner=$('#ownerFilter').value,cat=$('#categoryFilter').value;$('#kanban').innerHTML=stages.map(s=>{let arr=items.filter(x=>x.stage===s&&(!term||`${x.title} ${x.supplier}`.toLowerCase().includes(term))&&(owner==='all'||x.owner===owner)&&(cat==='all'||x.category===cat));return `<div class="column" data-stage="${s}"><div class="column-header"><span>${stageMeta[s][0]} ${stageMeta[s][1]}</span><span class="count">${arr.length}</span></div>${arr.map(card).join('')}</div>`}).join('');bindDnD();renderAttention()}
function renderAttention(){let risky=items.filter(x=>x.stage!=='CONCLUÍDO'&&(urgency(x.due)||urgency(x.payment)));let top=risky.sort((a,b)=>new Date(a.payment||a.due)-new Date(b.payment||b.due))[0];$('#alertBubble').style.display=risky.length?'block':'none';if(top){let field=urgency(top.payment)==='late'||urgency(top.due)==='late'?'atrasado':'próximo';$('#attention').className='attention visible';$('#attention').innerHTML=`<span>🚨</span><span><b>${risky.length} item${risky.length>1?'s':''} precisa${risky.length>1?'m':''} da sua atenção.</b> ${top.title} tem prazo ${field}.</span><button onclick="openEdit(${top.id})">Ver item →</button>`}else $('#attention').className='attention'}
function renderDashboard(){let nums=stages.map(s=>items.filter(x=>x.stage===s).length);let est=items.reduce((a,x)=>a+(+x.value||0),0), contracted=items.filter(x=>['CONTRATADO','CONCLUÍDO'].includes(x.stage)).reduce((a,x)=>a+(+x.value||0),0),paid=items.reduce((a,x)=>a+(+x.paid||0),0),days=Math.max(0,Math.ceil((new Date('2026-10-25T12:00:00')-today)/864e5));let urgent=items.filter(x=>urgency(x.due)||urgency(x.payment)).slice(0,4);$('#dashboardContent').innerHTML=`<div class="summary-grid"><div class="stat"><small>DIAS PARA A FESTA</small><b>${days}</b></div>${stages.map((s,i)=>`<div class="stat"><small>${stageMeta[s][0]} ${s}</small><b>${nums[i]}</b></div>`).join('')}</div><div class="dashboard-grid"><div><div class="panel"><h3>💰 Visão financeira</h3><div class="financial-summary"><div><small>Planejado</small><b>${money(est)}</b></div><div><small>Contratado</small><b>${money(contracted)}</b></div><div><small>Já pago</small><b>${money(paid)}</b></div></div></div><div class="panel" style="margin-top:18px"><h3>👥 Por responsável</h3>${['Bruno','Mariana','Bruno + Mariana'].map(o=>{let q=items.filter(x=>x.owner===o&&x.stage!=='CONCLUÍDO').length;return `<div class="task-row">${ownerAvatar(o)}<div class="task-info"><b>${o==='Bruno + Mariana'?'Compartilhado':o}</b><small>${q} tarefa${q!==1?'s':''} aberta${q!==1?'s':''}</small></div></div>`}).join('')}</div></div><div class="panel"><h3>🚨 Atenção agora</h3>${urgent.length?urgent.map(x=>`<div class="task-row"><span class="priority-dot ${urgency(x.payment||x.due)}"></span><div class="task-info"><b>${x.title}</b><small>${x.payment?'Pagamento':'Prazo'}: ${date(x.payment||x.due)} · ${x.owner}</small></div></div>`).join(''):'Tudo tranquilo por aqui ✨'}</div></div>`}
function renderTasks(){let arr=items.filter(x=>(x.owner==='Bruno'||x.owner==='Bruno + Mariana')&&x.stage!=='CONCLUÍDO').sort((a,b)=>new Date(a.payment||a.due)-new Date(b.payment||b.due));$('#taskCount').textContent=arr.length;$('#tasksContent').innerHTML=arr.map(x=>`<div class="panel task-row"><span class="priority-dot ${urgency(x.payment||x.due)}"></span><div class="task-info"><b>${iconOf(x.category)} ${x.title}</b><small>${x.owner==='Bruno + Mariana'?'Compartilhado com Mariana':'Responsável: Bruno'} · ${x.stage}</small></div><div><small>${x.payment?'Pagamento':'Prazo'}</small><b>${date(x.payment||x.due)}</b></div><button class="secondary" onclick="openEdit(${x.id})">Abrir</button></div>`).join('')||'<div class="panel">Nenhuma tarefa pendente. Que delícia! ✨</div>'}
function renderCalendar(){let events=items.filter(x=>x.due||x.payment);let cells=[];for(let i=1;i<=31;i++){let day=`2026-10-${String(i).padStart(2,'0')}`;cells.push(`<div class="day"><b>${i}</b>${events.filter(x=>x.due===day||x.payment===day).map(x=>`<div class="event ${x.payment===day?'payment':x.due===day&&x.stage==='CONTRATADO'?'delivery':''}" onclick="openEdit(${x.id})">${x.payment===day?'💳':'📅'} ${x.title}</div>`).join('')}</div>`)}$('#calendarContent').innerHTML=`<div class="calendar"><div class="calendar-head"><span>DOM</span><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span></div><div class="calendar-grid">${Array(4).fill('<div class="day muted"></div>').join('')}${cells.join('')}</div></div>`}
function renderFinance(){let total=items.reduce((a,x)=>a+(+x.value||0),0), paid=items.reduce((a,x)=>a+(+x.paid||0),0), groups={};items.forEach(x=>groups[x.category]=(groups[x.category]||0)+(+x.value||0));let max=Math.max(...Object.values(groups),1);let payments=items.filter(x=>x.payment).sort((a,b)=>new Date(a.payment)-new Date(b.payment));$('#financeContent').innerHTML=`<div class="financial-summary" style="margin-bottom:18px"><div><small>ORÇAMENTO TOTAL</small><b>${money(total)}</b></div><div><small>TOTAL PAGO</small><b>${money(paid)}</b></div><div><small>A PAGAR</small><b>${money(total-paid)}</b></div></div><div class="finance-layout"><div class="panel"><h3>Por categoria</h3>${Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="bar-row"><span>${iconOf(n)} ${n}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${money(v)}</b></div>`).join('')}</div><div class="panel"><h3>Próximos pagamentos</h3>${payments.map(x=>`<div class="payment-row"><span class="priority-dot ${urgency(x.payment)}"></span><div class="task-info"><b>${x.title}</b><small>${x.supplier||x.owner}</small></div><div><b>${money((x.value||0)-(x.paid||0))}</b><small>${date(x.payment)}</small></div></div>`).join('')||'Nenhum pagamento programado.'}</div></div>`}
function renderAll(){renderBoard();renderDashboard();renderTasks();renderCalendar();renderFinance();localStorage.setItem('olga-items',JSON.stringify(items))}
function bindDnD(){document.querySelectorAll('.card').forEach(c=>{c.addEventListener('dragstart',()=>c.classList.add('dragging'));c.addEventListener('dragend',()=>c.classList.remove('dragging'));c.addEventListener('click',()=>openEdit(+c.dataset.id))});document.querySelectorAll('.column').forEach(col=>{col.addEventListener('dragover',e=>e.preventDefault());col.addEventListener('drop',e=>{let c=document.querySelector('.dragging');if(c)moveItem(+c.dataset.id,col.dataset.stage)})})}
function moveItem(id,target){let x=items.find(i=>i.id===id);if(x.stage===target)return;if(target==='ORÇADO'&&!x.supplier){editId=id;selectedCategory=x.category;openModal('quote');return}if(target==='CONTRATADO'&&(!x.value||!x.payment)){editId=id;selectedCategory=x.category;openModal('contract');return}if(target==='CONCLUÍDO'&&((x.value||0)>(x.paid||0)||!x.due)){alert('Ainda há pendências críticas: confirme a entrega e registre todos os pagamentos antes de concluir.');return}x.stage=target;save()}
function input(label,key,type='text',wide=false,required=false,value=''){return `<label class="${wide?'wide':''}">${label}<input name="${key}" type="${type}" value="${value||''}" ${required?'required':''}></label>`}
function openModal(mode='new'){let x=editId?items.find(i=>i.id===editId):null;let modal=$('#itemModal');if(mode==='new'&&!selectedCategory){$('#modalEyebrow').textContent='NOVO ITEM';$('#modalTitle').textContent='O que você está planejando?';$('#formBody').innerHTML=`<div class="category-grid">${categories.map(([i,n])=>`<button type="button" class="category-choice" data-category="${n}"><span>${i}</span>${n}</button>`).join('')}</div>`;$('#saveBtn').textContent='Continuar';$('#saveBtn').type='button';document.querySelectorAll('.category-choice').forEach(b=>b.onclick=()=>{selectedCategory=b.dataset.category;openModal('details')})}else{let contracting=mode==='contract',quoting=mode==='quote';$('#modalEyebrow').textContent=quoting?'ORÇAMENTO':contracting?'CONFIRMAR CONTRATAÇÃO':x?'EDITAR ITEM':'NOVO ITEM';$('#modalTitle').textContent=x?x.title:`${iconOf(selectedCategory)} ${selectedCategory}`;let base=`<div class="form-grid">${input('Nome do item','title','text',true,true,x?.title)}${input('Responsável','owner','text',false,true,x?.owner||'')}${input('Fornecedor / loja','supplier','text',false,false,x?.supplier||'')}${input(selectedCategory==='Lembrancinhas'||selectedCategory==='Embalagens'?'Quantidade':'Quantidade / pessoas','quantity','number',false,false,x?.quantity)}${input('Valor estimado / final','value','number',false,false,x?.value)}${input('Data do prazo / entrega','due','date',false,false,x?.due)}${input('Próximo pagamento','payment','date',false,false,x?.payment)}${input('Valor já pago','paid','number',false,false,x?.paid)}${selectedCategory==='Decoração'?input('Referência visual / link','reference','url',true,false,x?.reference):''}<label class="wide">Observações<textarea name="note">${x?.note||''}</textarea></label></div>`;if(contracting)base=`<p class="modal-description">Registre o compromisso financeiro e a data de execução para contratar este item.</p>${base}`;if(quoting)base=`<p class="modal-description">Para avançar, informe fornecedor e uma proposta concreta.</p>${base}`;$('#formBody').innerHTML=base;let owner=$('[name=owner]');owner.outerHTML=`<label>Responsável<select name="owner" required><option ${x?.owner==='Bruno'?'selected':''}>Bruno</option><option ${x?.owner==='Mariana'?'selected':''}>Mariana</option><option ${(x?.owner||'Bruno + Mariana')==='Bruno + Mariana'?'selected':''}>Bruno + Mariana</option></select></label>`;$('#saveBtn').type='submit';$('#saveBtn').textContent=x?'Salvar alterações':contracting?'Confirmar contratação':'Criar item'}modal.showModal();$('#modalBackdrop').classList.add('show')}
function closeModal(){selectedCategory='';editId=null;$('#itemModal').close();$('#shareModal').close();$('#modalBackdrop').classList.remove('show')}
window.openEdit=id=>{editId=id;selectedCategory=items.find(x=>x.id===id).category;openModal('details')};
$('#addBtn').onclick=()=>{editId=null;selectedCategory='';openModal()};$('#shareBtn').onclick=()=>{$('#shareModal').showModal();$('#modalBackdrop').classList.add('show')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);$('#modalBackdrop').onclick=closeModal;$('#copyBtn').onclick=e=>{navigator.clipboard?.writeText('festadaolga.app/convite/mariana');e.target.textContent='Copiado!'};
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));if(!d.owner){alert('Todo item precisa de responsável.');return}if(editId){let x=items.find(i=>i.id===editId);Object.assign(x,d);if(x.stage==='IDEALIZADO'&&x.supplier&&x.value)x.stage='ORÇADO';if(x.stage==='ORÇADO'&&x.supplier&&x.value&&x.payment)x.stage='CONTRATADO'}else items.push({id:Date.now(),stage:'AÇÃO',...d,value:+d.value||0,paid:+d.paid||0});closeModal();save()});
$('.nav-link[data-view=board]').onclick=()=>{};document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link,.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.view).classList.add('active');let names={board:['Planejamento','Organize cada detalhe da festa'],dashboard:['Visão geral','A festa em um só olhar'],tasks:['Minhas tarefas','Tudo que precisa da sua atenção'],calendar:['Calendário','Seus compromissos'],finance:['Financeiro','Controle de gastos']};$('#heading').innerHTML=`<b>${names[b.dataset.view][0]}</b><span>${names[b.dataset.view][1]}</span>`});
['search','ownerFilter','categoryFilter'].forEach(id=>$('#'+id).addEventListener('input',renderBoard));$('#clearFilters').onclick=()=>{$('#search').value='';$('#ownerFilter').value='all';$('#categoryFilter').value='all';renderBoard()};categories.forEach(([,c])=>$('#categoryFilter').insertAdjacentHTML('beforeend',`<option>${c}</option>`));$('#alertBtn').onclick=()=>{document.querySelector('.nav-link[data-view=dashboard]').click();window.scrollTo({top:0,behavior:'smooth'})};$('#resetBtn').onclick=()=>{if(confirm('Restaurar os dados de demonstração? As alterações salvas serão substituídas.')){items=structuredClone(initial);save()}};$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');renderAll();
